# Generated by Django 6.0.1 on 2026-03-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_passwordresetrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="PasswordResetRequest",
        ),
    ]
