# Generated by Django 6.0.1 on 2026-03-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_is_email_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_email_verified",
        ),
    ]
