# Generated by Django 6.0.1 on 2026-03-06 17:24

import django.db.models.deletion
from django.db import migrations, models


def migrate_product_categories_to_fk(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Category = apps.get_model("products", "Category")

    uncategorized, _ = Category.objects.get_or_create(
        name="Uncategorized",
        defaults={"status": "Active"},
    )

    for product in Product.objects.all():
        category_name = (product.category or "").strip()
        if not category_name:
            category = uncategorized
        else:
            category, _ = Category.objects.get_or_create(
                name=category_name,
                defaults={"status": "Active"},
            )

        product.category_fk = category
        product.save(update_fields=["category_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.category",
            ),
        ),
        migrations.RunPython(migrate_product_categories_to_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="category_fk",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.category",
            ),
        ),
    ]
