# Generated by Django 6.0.1 on 2026-03-10 17:30

import django.db.models.deletion
from django.db import migrations, models


def convert_product_supplier_to_fk(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Supplier = apps.get_model("products", "Supplier")

    for product in Product.objects.exclude(supplier__isnull=True).exclude(supplier__exact=""):
        supplier, _ = Supplier.objects.get_or_create(name=product.supplier)
        product.supplier = str(supplier.id)
        product.save(update_fields=["supplier"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_supplier_purchase_purchaseitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="lead_time_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supplier",
            name="minimum_order_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(convert_product_supplier_to_fk, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.supplier",
            ),
        ),
    ]
